# For standard
# runtime: nodejs10
# env: standard

# For Flex
runtime: nodejs10
env: standard

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
     
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
    # secure: always
    # redirect_http_response_code: 301
    # script: auto
    # This one added newly for flex
    

# For Flex

# liveness_check:
#   path: "/liveness_check"
#   check_interval_sec: 30
#   timeout_sec: 4
#   failure_threshold: 2
#   success_threshold: 2
